import type { IDatabase } from "./database.js"

/** The 16-byte magic header every SQLite database file starts with. */
const SQLITE_HEADER = "SQLite format 3\0"

/**
 * Validates that `bytes` begin with the SQLite file magic header.
 *
 * Pure, synchronous, no I/O — call this before handing an untrusted file to
 * {@link replaceDatabaseContents} so a garbage file (wrong attachment, a
 * half-downloaded archive, …) can't be ATTACHed and silently destroy the live
 * database inside the replace transaction.
 *
 * @returns `true` if the bytes look like a SQLite database.
 */
export function isSqliteFile(bytes: Uint8Array): boolean {
  if (bytes.length < SQLITE_HEADER.length) return false
  for (let i = 0; i < SQLITE_HEADER.length; i++) {
    if (bytes[i] !== SQLITE_HEADER.charCodeAt(i)) return false
  }
  return true
}

/**
 * Replaces all contents of the live database (`main`) with the contents of
 * another SQLite database, by schema reflection.
 *
 * Platform-agnostic core of "import a database file": every operation runs
 * against the supplied {@link IDatabase}; the caller is responsible for the
 * platform glue (staging the file to a path/handle, resolving an absolute path
 * for ATTACH, and reloading afterwards). The imported database is referenced by
 * the SQL schema alias `attachedAs` (default `"imported"`), which the caller
 * must have ATTACHed beforehand, and DETACH afterwards.
 *
 * Algorithm (mirrors a file-swap + migrate, but at the SQL layer):
 *  1. Drop every schema object in `main` (triggers → views → indices → tables),
 *     leaving SQLite-internal `sqlite_%` objects untouched.
 *  2. Re-create every table from `<attachedAs>.sqlite_master` using its stored,
 *     unqualified CREATE statement (which targets `main`), then copy rows 1:1.
 *     The `migrations` table comes along, so a later migration run can bring an
 *     older imported schema forward.
 *  3. Re-create non-table objects (indices, views, triggers) in dependency
 *     order.
 *
 * Foreign-key enforcement is disabled for the duration and the whole rebuild
 * runs in a single transaction (rolled back on throw). `PRAGMA`/`ATTACH` must
 * run outside a transaction, which is why ATTACH/DETACH are left to the caller.
 *
 * @param db - The live database to rewrite.
 * @param attachedAs - SQL schema alias of the already-ATTACHed source database.
 */
export async function replaceDatabaseContents(
  db: IDatabase,
  attachedAs = "imported"
): Promise<void> {
  await db.execute("PRAGMA foreign_keys = OFF")
  try {
    await db.transaction(async () => {
      // 1. Drop every schema object in `main`. Order matters: triggers and
      // views can reference tables; indices need their target table to exist
      // (so they precede tables). `sqlite_%` is SQLite-internal — never touched.
      const mainObjects = await db.query<{ type: string; name: string }>(
        `SELECT type, name
           FROM main.sqlite_master
           WHERE name NOT LIKE 'sqlite_%'
           ORDER BY CASE type
             WHEN 'trigger' THEN 1
             WHEN 'view'    THEN 2
             WHEN 'index'   THEN 3
             WHEN 'table'   THEN 4
             ELSE 5
           END`
      )
      for (const { type, name } of mainObjects) {
        await db.execute(`DROP ${type.toUpperCase()} IF EXISTS main."${name}"`)
      }

      // 2. Re-create tables from the source's sqlite_master. The stored CREATE
      // statement is unqualified and runs against `main` (the default schema),
      // so `main` ends up with the source's exact schema — including the
      // `migrations` table with its version history. Then copy rows 1:1.
      const importedTables = await db.query<{ name: string; sql: string }>(
        `SELECT name, sql FROM ${attachedAs}.sqlite_master
           WHERE type = 'table'
             AND sql IS NOT NULL
             AND name NOT LIKE 'sqlite_%'`
      )
      for (const { name, sql } of importedTables) {
        await db.execute(sql)
        await db.execute(`INSERT INTO main."${name}" SELECT * FROM ${attachedAs}."${name}"`)
      }

      // 3. Non-table objects in dependency order (indices need tables; views
      // may reference tables; triggers can reference either). Autogenerated
      // `sqlite_autoindex_*` rows have NULL sql and reappear on table create.
      for (const objectType of ["index", "view", "trigger"] as const) {
        const objects = await db.query<{ sql: string }>(
          `SELECT sql FROM ${attachedAs}.sqlite_master
             WHERE type = ?
               AND sql IS NOT NULL
               AND name NOT LIKE 'sqlite_%'`,
          [objectType]
        )
        for (const { sql } of objects) {
          await db.execute(sql)
        }
      }
    })
  } finally {
    await db.execute("PRAGMA foreign_keys = ON")
  }
}
