// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capture} from '../models';

export function ListAudioDevices():Promise<Array<capture.Device>>;

export function StartRecording(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopRecording():Promise<string>;
