// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListAudioDevices() {
  return window['go']['main']['App']['ListAudioDevices']();
}

export function StartRecording(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2, arg3);
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
