#!/usr/bin/env bash
# infra/observability/scripts/deploy.sh
#
# Idempotent deploy of the observability stack onto a single VPS.
#
#   ./deploy.sh <obs-ip> [--region eu] [--ssh-user root] [--ssh-key ~/.ssh/id_ed25519]
#
# What it does:
#   1. Validate args, source config/<region>.env + config/shared.env.
#   2. SSH-bootstrap the host (docker, ufw, chrony, log rotation).
#   3. Render *.template files (Caddyfile, prometheus.yml, datasources.yml).
#   4. rsync the compose tree + scripts to /opt/shruti-observability.
#   5. Idempotently generate secrets (encryption_key etc).
#   6. Build a runtime .env on the host from secrets + config + shared.
#   7. docker compose up -d.
#   8. Healthcheck the stack.
#   9. Report URLs.
#
# Safe to re-run any number of times — secrets are never overwritten.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
UNIT="$ROOT/observability"
SHARED="$ROOT/shared"

# shellcheck source=../../shared/lib/deploy-common.sh
source "$SHARED/lib/deploy-common.sh"
# shellcheck source=../../shared/lib/render-templates.sh
source "$SHARED/lib/render-templates.sh"

# ──────────────────────────────────────────────────────────────────────
# args
# ──────────────────────────────────────────────────────────────────────
REGION=eu
SSH_USER=root
SSH_KEY=""
TARGET_IP=""

while [ $# -gt 0 ]; do
  case "$1" in
    --region)   REGION="$2"; shift 2 ;;
    --ssh-user) SSH_USER="$2"; shift 2 ;;
    --ssh-key)  SSH_KEY="$2"; shift 2 ;;
    -h|--help)
      sed -n '4,15p' "$0"; exit 0 ;;
    -*)
      fail "unknown flag: $1" ;;
    *)
      [ -z "$TARGET_IP" ] || fail "extra positional arg: $1"
      TARGET_IP="$1"; shift ;;
  esac
done

[ -n "$TARGET_IP" ] || fail "usage: ./deploy.sh <obs-ip> [--region eu]"
[ -f "$UNIT/config/${REGION}.env" ] || fail "no config/${REGION}.env"
[ -f "$UNIT/config/shared.env" ] || fail "no config/shared.env — copy from shared.env.example"

# ──────────────────────────────────────────────────────────────────────
# load config (export everything for envsubst)
# ──────────────────────────────────────────────────────────────────────
set -a
# shellcheck source=/dev/null
source "$UNIT/config/${REGION}.env"
# shellcheck source=/dev/null
source "$UNIT/config/shared.env"
set +a

require_vars REGION TAILNET_DOMAIN OBS_TS_IP PROD_HOST_TS_IP \
             CF_API_TOKEN TG_BOT_TOKEN TG_CHAT_ID GRAFANA_ADMIN_PASSWORD

if [ -z "$SSH_KEY" ]; then
  if [ -n "${WORKSPACE_CWD:-}" ] && [ -f "${WORKSPACE_CWD}/../.config/ssh/id_ed25519" ]; then
    SSH_KEY="${WORKSPACE_CWD}/../.config/ssh/id_ed25519"
  else
    SSH_KEY="$HOME/.ssh/id_ed25519"
  fi
fi
[ -f "$SSH_KEY" ] || fail "ssh key not found: $SSH_KEY"

SSH_TARGET="$SSH_USER@$TARGET_IP"
SSH_OPTS=(-o StrictHostKeyChecking=accept-new -o ServerAliveInterval=30 -i "$SSH_KEY")
REMOTE_DIR="/opt/shruti-observability"

# ──────────────────────────────────────────────────────────────────────
# 1. Bootstrap the host
# ──────────────────────────────────────────────────────────────────────
ensure_target_host_ready

# ──────────────────────────────────────────────────────────────────────
# 2. Render *.template files locally
# ──────────────────────────────────────────────────────────────────────
log "Rendering templates..."
render_templates_in "$UNIT/compose"

# ──────────────────────────────────────────────────────────────────────
# 3. rsync the unit + the shared library to the target host
# ──────────────────────────────────────────────────────────────────────
rsync_to_target "$UNIT"   "$REMOTE_DIR"
rsync_to_target "$SHARED" "$REMOTE_DIR/_shared"

# ──────────────────────────────────────────────────────────────────────
# 4. Idempotently generate secrets on the host
# ──────────────────────────────────────────────────────────────────────
ensure_secrets "$REMOTE_DIR/secrets" \
  encryption_key:"openssl rand -hex 32" \
  nextauth_secret:"openssl rand -base64 32 | tr -d '\\n'" \
  salt:"openssl rand -base64 32 | tr -d '\\n'" \
  clickhouse_password:"openssl rand -hex 24" \
  postgres_lf_password:"openssl rand -hex 24" \
  minio_root_password:"openssl rand -hex 24" \
  langfuse_public_key:"printf 'pk-lf-%s' \"\$(uuidgen)\"" \
  langfuse_secret_key:"printf 'sk-lf-%s' \"\$(uuidgen)\""

# ──────────────────────────────────────────────────────────────────────
# 5. Build runtime .env on the host (compose --env-file pick this up)
# ──────────────────────────────────────────────────────────────────────
log "Composing runtime .env on host..."
ssh_pipe <<REMOTE
set -euo pipefail
cd "$REMOTE_DIR"
secrets_dir="$REMOTE_DIR/secrets"

cat > compose/.env <<EOF
# AUTO-GENERATED by deploy.sh — do not edit by hand
REGION=$REGION
TAILNET_DOMAIN=$TAILNET_DOMAIN
OBS_TS_IP=$OBS_TS_IP
PROD_HOST_TS_IP=$PROD_HOST_TS_IP
CF_API_TOKEN=$CF_API_TOKEN
TG_BOT_TOKEN=$TG_BOT_TOKEN
TG_CHAT_ID=$TG_CHAT_ID
GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio}
LANGFUSE_INIT_USER_EMAIL=$LANGFUSE_INIT_USER_EMAIL
LANGFUSE_INIT_USER_NAME=$LANGFUSE_INIT_USER_NAME
LANGFUSE_INIT_USER_PASSWORD=$LANGFUSE_INIT_USER_PASSWORD
ENCRYPTION_KEY=\$(cat \$secrets_dir/encryption_key)
NEXTAUTH_SECRET=\$(cat \$secrets_dir/nextauth_secret)
SALT=\$(cat \$secrets_dir/salt)
CLICKHOUSE_PASSWORD=\$(cat \$secrets_dir/clickhouse_password)
POSTGRES_LF_PASSWORD=\$(cat \$secrets_dir/postgres_lf_password)
MINIO_ROOT_PASSWORD=\$(cat \$secrets_dir/minio_root_password)
LANGFUSE_PUBLIC_KEY=\$(cat \$secrets_dir/langfuse_public_key)
LANGFUSE_SECRET_KEY=\$(cat \$secrets_dir/langfuse_secret_key)
EOF
chmod 600 compose/.env

# Loki volume needs to be owned by UID 10001 (grafana/loki runs non-root).
docker run --rm -v shruti-observability_loki-data:/loki alpine \
  chown -R 10001:10001 /loki 2>/dev/null || true
REMOTE
ok "runtime .env written"

# ──────────────────────────────────────────────────────────────────────
# 6. docker compose up
# ──────────────────────────────────────────────────────────────────────
compose_up "$REMOTE_DIR"

# ──────────────────────────────────────────────────────────────────────
# 7. Healthchecks
# ──────────────────────────────────────────────────────────────────────
wait_healthcheck "http://localhost:2019/config/"                    60  caddy
wait_healthcheck "http://localhost:9090/-/ready"                    60  prometheus
wait_healthcheck "http://localhost:3100/ready"                      60  loki
wait_healthcheck "http://${OBS_TS_IP}:3100/ready"                   30  "loki ingest (Tailscale)"
# Grafana via docker exec — port 3000 is not bound on host.
ssh_run "docker exec grafana wget --spider -q http://localhost:3000/api/health" \
  && ok "grafana healthy" || warn "grafana not yet healthy"
# Langfuse migrations may still be in flight — give 180s.
ssh_run "for i in \$(seq 1 60); do docker exec langfuse-web wget --spider -q http://localhost:3000/api/public/health 2>/dev/null && break || sleep 3; done" \
  && ok "langfuse-web healthy" || warn "langfuse-web not yet healthy (ClickHouse migration may still be running)"

# ──────────────────────────────────────────────────────────────────────
# 8. Post-deploy hooks (idempotent infra-config re-asserts).
#     See infra/observability/scripts/post-deploy/README.md for the contract.
# ──────────────────────────────────────────────────────────────────────
HOOKS_DIR="$UNIT/scripts/post-deploy"
if [ -d "$HOOKS_DIR" ]; then
  log "Running post-deploy hooks..."
  # Hooks are sourced inside a subshell so they inherit the SSH_OPTS bash
  # array (which doesn't survive env-export across a fresh `bash $hook`
  # process) while still getting isolated exit-status semantics. SSH_TARGET /
  # REMOTE_DIR / REGION / TG_* / GRAFANA_ADMIN_PASSWORD / CF_* are already
  # in the environment (exported earlier by `set -a` and the deploy flow).
  shopt -s nullglob
  hooks=("$HOOKS_DIR"/[0-9]*.sh)
  shopt -u nullglob
  if [ "${#hooks[@]}" -eq 0 ]; then
    log "  (none)"
  else
    for hook in "${hooks[@]}"; do
      log "  • $(basename "$hook")"
      ( source "$hook" )
    done
  fi
  ok "Post-deploy hooks done"
fi

# ──────────────────────────────────────────────────────────────────────
# 9. Report
# ──────────────────────────────────────────────────────────────────────
report_urls "Observability stack deployed ($REGION)" \
  "https://grafana.${TAILNET_DOMAIN}" \
  "https://langfuse.${TAILNET_DOMAIN}" \
  "https://prometheus.${TAILNET_DOMAIN}" \
  "http://${OBS_TS_IP}:3100  (Loki ingest from prod-EU promtail)" \
  "http://${OBS_TS_IP}:3001  (Langfuse SDK push from prod-EU chat)"

cat <<NEXT

Next steps:
  1. On a brand-new host: run ./scripts/configure.sh --region $REGION
     to bootstrap Cloudflare DNS, materialise Langfuse API keys for the
     chat service, and run the 10-point smoke verification. Recurring
     config (Langfuse TTL, Grafana contact-point re-check) is now applied
     automatically by post-deploy hooks on every deploy.
  2. Then deploy the observability-agent unit on prod-EU so metrics and
     logs start flowing.
NEXT
