name: lectorium

# -------------------------------------------------------------------------- #
#                                  Framgents                                 #
# -------------------------------------------------------------------------- #

x-airflow-common:
  build:
    context: ../modules/services/airflow/
    dockerfile: Dockerfile
  volumes:
    - ../data/airflow/logs:/opt/airflow/logs
    - ../modules/services/airflow/dags:/opt/airflow/dags
    - ../modules/services/airflow/config:/opt/airflow/config
    - ../modules/services/airflow/plugins:/opt/airflow/plugins

# -------------------------------------------------------------------------- #
#                                  Services                                  #
# -------------------------------------------------------------------------- #

services:

  # ------------------------------- Development ---------------------------- #

  dev:
    image: mcr.microsoft.com/devcontainers/base:noble
    command: sleep 365d
    ports:
      - "80:80"
      - "443:443"
      - "8101:8101"
      - "8102:8102"
    networks:
      - lectorium
    volumes:
      - ../:/workspaces/lectorium
      - /tmp/lectorium:/tmp/lectorium
    depends_on:
      - couchdb
      - postgres
      - redis
      

  api:
    build:
      context: ../modules/
      dockerfile: ./services/api/Dockerfile

  admin:
    build:
      context: ../modules/
      dockerfile: ./apps/admin/Dockerfile

  landing:
    build:
      context: ../modules/
      dockerfile: ./apps/landing/Dockerfile

  # ----------------------------- Infrastructure --------------------------- #

  gateway:
    build:
      context: ../modules/
      dockerfile: ./services/gateway/Dockerfile
    environment:
      - LECTORIUM_CONFIG_TYPE=dev

  couchdb:
    build:
      context: ../modules/
      dockerfile: ./services/couchdb/service/Dockerfile
    ports:
      - 5984:5984

  couchdb-init:
    build:
      context: ../modules/
      dockerfile: ./services/couchdb/init/Dockerfile
    environment:
      LECTORIUM_CONTENT_MANAGER_EMAIL: contentManager@lectorium.dev
      LECTORIUM_CONTENT_MANAGER_PASSWORD: contentManager

  postgres:
    environment:
      LECTORIUM_POSTGRES_USER: lectorium
      LECTORIUM_POSTGRES_PASSWORD: lectorium
      LECTORIUM_POSTGRES_DB: lectorium

  airflow-webserver:
    build:
      context: ../modules/
      dockerfile: ./services/airflow/Dockerfile
    ports:
      - "8080:8080"

  airflow-scheduler:
    build:
      context: ../modules/
      dockerfile: ./services/airflow/Dockerfile

  airflow-worker:
    build:
      context: ../modules/
      dockerfile: ./services/airflow/Dockerfile

  airflow-triggerer:
    build:
      context: ../modules/
      dockerfile: ./services/airflow/Dockerfile

  airflow-init:
    build:
      context: ../modules/
      dockerfile: ./services/airflow/Dockerfile
    environment:
      LECTORIUM_AIRFLOW_DB_MIGRATE: 'true'
      LECTORIUM_AIRFLOW_WWW_USER_CREATE: 'true'
      LECTORIUM_AIRFLOW_WWW_USER_USERNAME: lectorium
      LECTORIUM_AIRFLOW_WWW_USER_PASSWORD: lectorium
