export {
  IconHomeFilled as IconHome,
  IconLayoutDashboardFilled as IconSearch,
  IconBookmarkFilled as IconBookmark,
  IconSettingsFilled as IconSettings,
  IconPlayerPlayFilled as IconPlay,
  IconWritingFilled as HighlightTextIcon,
  IconFileTextFilled as AnnotationIcon,
  IconBellFilled as BellIcon,
  IconClockFilled as ClockIcon,
  IconFlameFilled as FlameIcon,
  IconRosetteDiscountCheckFilled,
  IconHeadphonesFilled as HeadphonesIcon,
  IconWorldFilled as LanguageIcon,
  IconCloudFilled as CloudIcon,
  IconTrashFilled as TrashIcon,
  IconArchiveFilled as ArchiveIcon,
  IconFileDownloadFilled as DatabaseExportIcon,
  IconFileUploadFilled as DatabaseImportIcon,
  IconHelpCircleFilled as HelpIcon,
  IconBookFilled as BookIcon,
} from "@tabler/icons-vue"
