export {
  IconHomeFilled as IconHome,
  // A magnifier, because the tab is search. It used to be a dashboard grid
  // aliased under this name, which drew four squares and said nothing.
  IconSearch,
  IconBookmarkFilled as IconBookmark,
  IconSettingsFilled as IconSettings,
  IconPlayerPlayFilled as IconPlay,
  IconWritingFilled as HighlightTextIcon,
  IconFileTextFilled as AnnotationIcon,
  IconBellFilled as BellIcon,
  IconClockFilled as ClockIcon,
  IconFlameFilled as FlameIcon,
  IconRosetteDiscountCheckFilled,
  IconHeadphonesFilled as HeadphonesIcon,
  IconWorldFilled as LanguageIcon,
  IconCloudFilled as CloudIcon,
  IconTrashFilled as TrashIcon,
  IconArchiveFilled as ArchiveIcon,
  IconDownload,
  IconFileDownloadFilled as DatabaseExportIcon,
  IconFileUploadFilled as DatabaseImportIcon,
  IconHelpCircleFilled as HelpIcon,
  IconBookFilled as BookIcon,
  IconShieldFilled as ShieldIcon,
  IconMessageFilled as MessageIcon,
  IconArticleFilled as TranscriptIcon,
  IconMailFilled as MailIcon,
  IconBrandVk as VkIcon,
  IconBrandTelegram as TelegramIcon,
  IconWorldWww as StudioIcon,
} from "@tabler/icons-vue"
