-- Drops dict_resolution_cache, which memoized LLM-resolver decisions
-- (raw string → matched_id) inside the lake registry. A cache of dict
-- ids outside the catalog is a second source of truth: any manual
-- catalog edit (rename, merge, delete) leaves stale ids in it, which
-- resurface at the next metadata extract or force-commit (silent FK
-- violations or duplicate-creation).
--
-- Resolution goes name → id through the catalog directly at commit
-- time, with a trigram-prefilter on the catalog dict for the LLM's
-- candidate list. The lake holds no dict ids anywhere — payload_json
-- carries canonical names.
DROP TABLE IF EXISTS dict_resolution_cache;
