import type { LanguageCode, TrackId } from "@lib/domain/core.js"
import type { Author } from "@lib/domain/author.js"
import type { Track } from "@lib/domain/track.js"
import type { TrackAudio, TrackVariant } from "@lib/domain/trackVariant.js"
import { err, ok, type Result } from "@kit/core"

export interface PlayTrackInput {
  readonly track: Track
  readonly preferredLanguage?: LanguageCode
  /** Optional — used only for the system-player "author" label. */
  readonly author?: Author | null
  /** Override the generated playback item id. Defaults to `track:<id>`. */
  readonly itemId?: string
}

export type PlayTrackError = "no-audio-available"

/**
 * Pure description of "what to play". Generated by the `playTrack` use
 * case and consumed by the player store, which drives the audio port
 * and reactive UI state from these fields.
 */
export interface PlayTrackCommand {
  readonly trackId: TrackId
  readonly itemId: string
  readonly variant: TrackVariant
  readonly audio: TrackAudio
  readonly title: string
  readonly authorName: string
  readonly language: LanguageCode
  /**
   * `false` when the user asked for a `preferredLanguage` but no variant
   * with audio in that language existed and we fell back to the first
   * audible variant. UI can use this to surface "playing in <X> — your
   * preferred <Y> is unavailable" instead of silently changing language.
   * `true` when no preference was supplied, or the preferred variant
   * was used as-is.
   */
  readonly matchesPreferred: boolean
}

function pickVariantWithAudio(
  track: Track,
  preferred: LanguageCode | undefined
): TrackVariant | null {
  if (preferred) {
    const v = track.variants.find((x) => x.language === preferred && x.audio)
    if (v) return v
  }
  return track.variants.find((v) => v.audio) ?? null
}

function resolveAuthorName(author: Author | null | undefined, language: LanguageCode): string {
  if (!author) return ""
  return author.names.get(language) ?? author.names.values().next().value ?? ""
}

/**
 * Turn a Track + optional preferred language into a playback command.
 * Keeps the variant-selection rule, item-id scheme, and author-name
 * fallback chain in one testable place — the player store is then a
 * pure state container that dispatches this command through the audio
 * port.
 */
export async function playTrack(
  input: PlayTrackInput
): Promise<Result<PlayTrackCommand, PlayTrackError>> {
  const variant = pickVariantWithAudio(input.track, input.preferredLanguage)
  if (!variant || !variant.audio) return err("no-audio-available")

  const matchesPreferred =
    input.preferredLanguage === undefined || variant.language === input.preferredLanguage

  return ok({
    trackId: input.track.id,
    itemId: input.itemId ?? `track:${input.track.id}`,
    variant,
    audio: variant.audio,
    title: variant.title,
    authorName: resolveAuthorName(input.author, variant.language),
    language: variant.language,
    matchesPreferred,
  })
}
