#!/usr/bin/env bash
# infra/observability/scripts/lib/bootstrap-langfuse.sh
#
# Langfuse v3 provisions its own org, project, and API keys on first start
# via the LANGFUSE_INIT_* env vars (see compose/docker-compose.yml). The
# pre-shared public/secret keys are generated by deploy.sh into
# secrets/langfuse_public_key + secrets/langfuse_secret_key and surfaced
# to the langfuse-web container as LANGFUSE_PUBLIC_KEY / LANGFUSE_SECRET_KEY.
#
# This bootstrap step therefore:
#   1. Waits for Langfuse to be reachable (so we know headless init landed).
#   2. Re-emits the keys + project ID + host URL as a single env file at
#      secrets/langfuse-keys.env, which the chat service on prod-EU later
#      consumes verbatim.
#
# Required env (set by configure.sh):
#   REGION, TAILNET_DOMAIN, REMOTE_DIR
# shellcheck shell=bash

bootstrap_langfuse() {
  require_vars REGION TAILNET_DOMAIN REMOTE_DIR || return 1

  local api="https://langfuse.${TAILNET_DOMAIN}"
  local project_id="chat-${REGION}"

  log "Waiting for Langfuse at $api..."
  local i ok_flag=0
  for i in $(seq 1 90); do
    if ssh_run "curl -fs --max-time 5 -o /dev/null '$api/api/public/health'" 2>/dev/null; then
      ok "Langfuse reachable (headless init completed)"
      ok_flag=1
      break
    fi
    sleep 4
  done
  if [ "$ok_flag" -ne 1 ]; then
    warn "Langfuse never came up — keys file will still be written for retry"
  fi

  log "Materialising secrets/langfuse-keys.env for downstream chat service"
  ssh_run "PROJECT_ID=$(printf %q "$project_id") \
           API_URL=$(printf %q "$api") \
           SECRETS=$(printf %q "$REMOTE_DIR/secrets") \
           bash -s" <<'REMOTE'
set -euo pipefail
pub=$(cat "$SECRETS/langfuse_public_key")
sec=$(cat "$SECRETS/langfuse_secret_key")
install -m 600 /dev/null "$SECRETS/langfuse-keys.env"
cat > "$SECRETS/langfuse-keys.env" <<EOF
# AUTO-GENERATED by bootstrap-langfuse.sh — consumed by chat service on prod-EU
LANGFUSE_HOST=$API_URL
LANGFUSE_PROJECT_ID=$PROJECT_ID
LANGFUSE_PUBLIC_KEY=$pub
LANGFUSE_SECRET_KEY=$sec
EOF
echo "  · keys written to $SECRETS/langfuse-keys.env"
REMOTE
  ok "langfuse-keys.env ready"
}
