#!/usr/bin/env bash
# Generate a local-dev .env file for the lectorium stack.
#
# All vars in this file are LECTORIUM_-prefixed (project convention);
# docker-compose.yml unpacks each into the variable name the underlying
# image expects (POSTGRES_PASSWORD, DOMAIN, DATABASE_URL…) at container
# start-time.
#
# Idempotent: skips if infra/.env.dev already exists.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$ROOT/infra/.env.dev"

if [ -f "$ENV_FILE" ]; then
  echo "✓ $ENV_FILE already exists — leaving it alone."
  echo "  Delete it manually if you want a fresh password."
  exit 0
fi

PG_PASS=$(head -c 24 /dev/urandom | base64 | tr -d '/+=')

cat > "$ENV_FILE" <<EOF
# Generated by gen-dev-env.sh. Never commit.

LECTORIUM_POSTGRES_PASSWORD=$PG_PASS
LECTORIUM_ENV_FILE=../.env.dev
LECTORIUM_JWT_KEYS_DIR=../../../.config/lectorium/jwt
LECTORIUM_IMAGE_TAG=dev

OPENROUTER_API_KEY=
APP_SHARED_TOKEN=dev-token
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=us-east-1
EOF

chmod 600 "$ENV_FILE"
echo "✓ Wrote $ENV_FILE (mode 0600)"
echo "  LECTORIUM_POSTGRES_PASSWORD is a fresh 24-byte random string;"
echo "  existing dev postgres volumes (if any) won't recognize it —"
echo "  \`docker compose down -v\` to wipe them before \`up\`."
