#!/usr/bin/env bash
# Deploy the observability-agent (Promtail + 5 exporters) to prod-EU.
#
# Idempotent: rsync code, generate missing secrets, compose up. Run again
# any time to push new images / config.
#
# Usage:
#   SERVER_IP=<prod-eu-public-ip> ./scripts/deploy.sh
#   SERVER_IP=<ip> SKIP_BOOTSTRAP=1 ./scripts/deploy.sh    # host already has docker
#
# Required env / args:
#   SERVER_IP            public IP (used for SSH) — first arg also accepted
#   PROD_EU_TS_IP        Tailscale IP of prod-eu (where exporters listen)
#   OBS_TS_IP            Tailscale IP of obs (where Promtail pushes logs)
#   PG_EXPORTER_PASSWORD postgres `pg_exporter` user's password (must match
#                        what was set on the prod Postgres via init.sql or
#                        the docker exec ALTER — see README.md)
#
# Optional:
#   SERVER_USER          default root
#   SSH_KEY              default ~/.ssh/id_ed25519
#   SKIP_BOOTSTRAP       set to 1 if docker/compose-plugin already present
#                        (e.g. host is already hosting infra/app/)
#
# TODO(shared-lib): once infra/shared/lib/deploy-common.sh exists (Stream A),
# replace the inline bootstrap + rsync helpers here with `source` of that
# file. Kept self-contained for now so Stream B can ship independently.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_DIR="$ROOT/compose"

# Accept positional arg as a shortcut for SERVER_IP.
if [ "$#" -ge 1 ] && [ -z "${SERVER_IP:-}" ]; then
  SERVER_IP="$1"
fi

SERVER_IP="${SERVER_IP:?SERVER_IP env var required (or pass as first arg)}"
SERVER_USER="${SERVER_USER:-root}"
PROD_EU_TS_IP="${PROD_EU_TS_IP:?PROD_EU_TS_IP must be set (Tailscale IP of prod-eu)}"
OBS_TS_IP="${OBS_TS_IP:?OBS_TS_IP must be set (Tailscale IP of obs)}"
PG_EXPORTER_PASSWORD="${PG_EXPORTER_PASSWORD:?PG_EXPORTER_PASSWORD must be set}"
SKIP_BOOTSTRAP="${SKIP_BOOTSTRAP:-0}"

if [ -z "${SSH_KEY:-}" ]; then
  if [ -n "${WORKSPACE_CWD:-}" ] && [ -f "${WORKSPACE_CWD}/../.config/ssh/id_ed25519" ]; then
    SSH_KEY="${WORKSPACE_CWD}/../.config/ssh/id_ed25519"
  else
    SSH_KEY="$HOME/.ssh/id_ed25519"
  fi
fi
[ -f "$SSH_KEY" ] || { echo "deploy.sh: SSH key not found at $SSH_KEY" >&2; exit 1; }

REMOTE_DIR="/opt/shruti-obs-agent"
SSH_OPTS=(-o "StrictHostKeyChecking=accept-new" -o "ServerAliveInterval=30" -i "$SSH_KEY")
SSH_TARGET="$SERVER_USER@$SERVER_IP"

ssh_run() { ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "$@"; }

# ── 1. SSH up; bootstrap docker if needed. ────────────────────────────
echo "→ Waiting for SSH on $SERVER_IP..."
for i in $(seq 1 60); do
  if ssh "${SSH_OPTS[@]}" "$SSH_TARGET" 'echo ok' >/dev/null 2>&1; then
    echo "  SSH ready."
    break
  fi
  sleep 2
done

if [ "$SKIP_BOOTSTRAP" != "1" ]; then
  echo "→ Ensuring docker + compose plugin installed..."
  ssh_run 'bash -s' <<'BOOTSTRAP'
set -euo pipefail
if ! command -v docker >/dev/null 2>&1; then
  apt-get update -y
  apt-get install -y docker.io docker-compose-plugin
  systemctl enable --now docker
fi
if ! docker compose version >/dev/null 2>&1; then
  apt-get install -y docker-compose-plugin
fi
BOOTSTRAP
else
  echo "→ Skipping host bootstrap (SKIP_BOOTSTRAP=1)."
fi

# ── 2. Verify chat-stack docker network exists. ───────────────────────
# postgres-exporter / redis-exporter / blackbox-exporter all attach to
# `shruti_shruti`. If infra/app/ hasn't been deployed first, this
# rsync still succeeds but `compose up` will fail with a clear error.
echo "→ Checking shruti_shruti docker network exists on host..."
if ! ssh_run "docker network inspect shruti_shruti >/dev/null 2>&1"; then
  cat >&2 <<EOF
deploy.sh: docker network 'shruti_shruti' not found on $SERVER_IP.
  observability-agent needs the chat-stack network. Deploy infra/app/
  first (it creates the network), then re-run this script.
EOF
  exit 2
fi

# ── 3. Push code (compose configs + this script). ─────────────────────
echo "→ Syncing $ROOT → $SSH_TARGET:$REMOTE_DIR ..."
ssh_run "mkdir -p $REMOTE_DIR"
rsync -az --delete \
  -e "ssh ${SSH_OPTS[*]}" \
  --exclude '.env' \
  --exclude '*.swp' \
  "$ROOT/" "$SSH_TARGET:$REMOTE_DIR/"

# ── 4. Render .env on host (idempotent — overwritten each deploy). ────
echo "→ Writing $REMOTE_DIR/.env ..."
ssh_run "umask 077 && cat > $REMOTE_DIR/.env" <<EOF
# Generated by infra/observability-agent/scripts/deploy.sh at $(date -u +%FT%TZ).
# Do not edit on host — re-run deploy.sh to update.
PROD_EU_TS_IP=$PROD_EU_TS_IP
OBS_TS_IP=$OBS_TS_IP
PG_EXPORTER_PASSWORD=$PG_EXPORTER_PASSWORD
EOF

# ── 5. Pull images + bring up the stack. ──────────────────────────────
echo "→ docker compose pull + up -d ..."
ssh_run "cd $REMOTE_DIR/compose && docker compose --env-file ../.env pull"
ssh_run "cd $REMOTE_DIR/compose && docker compose --env-file ../.env up -d"

# ── 6. Smoke check: all five exporters answer on Tailscale IP. ────────
echo "→ Waiting for exporter endpoints to come up..."
ENDPOINTS=(
  "$PROD_EU_TS_IP:9100/metrics      node-exporter"
  "$PROD_EU_TS_IP:8090/metrics      cadvisor"
  "$PROD_EU_TS_IP:9187/metrics      postgres-exporter"
  "$PROD_EU_TS_IP:9121/metrics      redis-exporter"
  "$PROD_EU_TS_IP:9115/metrics      blackbox-exporter"
  "$PROD_EU_TS_IP:9080/metrics      promtail"
)
for entry in "${ENDPOINTS[@]}"; do
  url=$(awk '{print $1}' <<<"$entry")
  name=$(awk '{print $2}' <<<"$entry")
  for i in $(seq 1 30); do
    if ssh_run "curl -fs --max-time 3 http://$url -o /dev/null"; then
      echo "  ✓ $name ($url)"
      break
    fi
    [ "$i" = "30" ] && { echo "  ✗ $name ($url) did not respond after 60s" >&2; }
    sleep 2
  done
done

echo
echo "Deploy complete."
echo "  Promtail is pushing logs to http://$OBS_TS_IP:3100/loki/api/v1/push"
echo "  Exporters listening on $PROD_EU_TS_IP (Tailscale IP) — scrape them from obs."
