#!/usr/bin/env bash
# Generate a local-dev .env file for the shruti stack.
#
# All vars in this file are SHRUTI_-prefixed (project convention);
# docker-compose.yml unpacks each into the variable name the underlying
# image expects (POSTGRES_PASSWORD, DOMAIN, DATABASE_URL…) at container
# start-time.
#
# Idempotent: skips if infra/app/.env.dev already exists.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
ENV_FILE="$ROOT/infra/app/.env.dev"

if [ -f "$ENV_FILE" ]; then
  echo "✓ $ENV_FILE already exists — leaving it alone."
  echo "  Delete it manually if you want a fresh password."
  exit 0
fi

PG_PASS=$(head -c 24 /dev/urandom | base64 | tr -d '/+=')
# profile sync service's OWN Postgres — separate DB, so its own password,
# generated the same way as the shared one above.
PROFILE_PG_PASS=$(head -c 24 /dev/urandom | base64 | tr -d '/+=')
# orchestrator + publish-service each own a separate Postgres (personal-library
# ingest/publish planes), so each gets its own generated password.
ORCHESTRATOR_PG_PASS=$(head -c 24 /dev/urandom | base64 | tr -d '/+=')
PUBLISH_PG_PASS=$(head -c 24 /dev/urandom | base64 | tr -d '/+=')
DISCOVERY_PG_PASS=$(head -c 24 /dev/urandom | base64 | tr -d '/+=')
# Read-only role the orchestrator postgres-exporter connects as. Required by the
# orchestrator-postgres init script, so compose refuses to start without it.
ORCHESTRATOR_PG_EXPORTER_PASS=$(head -c 24 /dev/urandom | base64 | tr -d '/+=')
# Admin shared secret for chat /status + /reindex. Generated (not a fixed
# "dev-token") so a fresh checkout doesn't ship a known admin token.
APP_TOKEN=$(head -c 24 /dev/urandom | base64 | tr -d '/+=')

cat > "$ENV_FILE" <<EOF
# Generated by gen-dev-env.sh. Never commit.

SHRUTI_POSTGRES_PASSWORD=$PG_PASS
SHRUTI_PROFILE_POSTGRES_PASSWORD=$PROFILE_PG_PASS
SHRUTI_ORCHESTRATOR_POSTGRES_PASSWORD=$ORCHESTRATOR_PG_PASS
SHRUTI_PUBLISH_POSTGRES_PASSWORD=$PUBLISH_PG_PASS
SHRUTI_DISCOVERY_POSTGRES_PASSWORD=$DISCOVERY_PG_PASS
ORCHESTRATOR_PG_EXPORTER_PASSWORD=$ORCHESTRATOR_PG_EXPORTER_PASS
SHRUTI_ENV_FILE=../.env.dev
SHRUTI_JWT_KEYS_DIR=../../../../.config/shruti/jwt
SHRUTI_IMAGE_TAG=dev

# Compose profiles — services in the base compose are tagged so the
# same file deploys two roles in prod (origin / proxy). For local dev
# we always want the full origin stack (auth, chat, cleanup-worker
# included). docker compose treats services without a profile as always
# active; tagged services need this opt-in.
COMPOSE_PROFILES=origin

# Caddy role + global host. Local dev usually skips caddy entirely
# (no prod overlay), but if anyone layers in docker-compose.prod.yml
# locally, default to origin so role-origin.conf imports.
SHRUTI_REGION_ROLE=origin

# S3 bucket — required by share-audio/share-video (\${SHRUTI_S3_BUCKET:?}),
# so the full \`make stack-up\` boots without hand-editing. Same bucket the
# app/chat read from prod.
SHRUTI_S3_BUCKET=shruti-engine

# Admin shared secret for chat /status + /reindex (random per checkout).
APP_SHARED_TOKEN=$APP_TOKEN

# API keys — left EMPTY here. Fill them from your secret manager; the field
# names match the variable names below.
# Without OPENROUTER_API_KEY + AWS_* the stack boots but chat can't embed/
# index (/readyz stays false) and share-* can't upload.
OPENROUTER_API_KEY=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=us-east-1
EOF

chmod 600 "$ENV_FILE"
echo "✓ Wrote $ENV_FILE (mode 0600)"
echo "  SHRUTI_POSTGRES_PASSWORD is a fresh 24-byte random string;"
echo "  existing dev postgres volumes (if any) won't recognize it —"
echo "  \`docker compose down -v\` to wipe them before \`up\`."
