name: shruti

# -------------------------------------------------------------------------- #
#                                  Services                                  #
# -------------------------------------------------------------------------- #

services:
  admin:
    image: ghcr.io/jiva-studio/shruti-admin:staging
    ports:
      - "80:80"

  couchdb:
    image: ghcr.io/jiva-studio/shruti-couchdb:staging

  airflow-webserver:
    image: ghcr.io/jiva-studio/shruti-airflow:staging

  airflow-scheduler:
    image: ghcr.io/jiva-studio/shruti-airflow:staging

  airflow-worker:
    image: ghcr.io/jiva-studio/shruti-airflow:staging

  airflow-triggerer:
    image: ghcr.io/jiva-studio/shruti-airflow:staging

  airflow-init:
    image: ghcr.io/jiva-studio/shruti-airflow:staging