name: shruti

# -------------------------------------------------------------------------- #
#                                  Services                                  #
# -------------------------------------------------------------------------- #

services:
  admin:
    image: ghcr.io/jiva-studio/shruti-admin:staging
    ports:
      - "80:80"
