name: shruti

# -------------------------------------------------------------------------- #
#                                  Services                                  #
# -------------------------------------------------------------------------- #

services:
  api:
    image: ghcr.io/akdasa-studios/shruti-api:staging

  admin:
    image: ghcr.io/akdasa-studios/shruti-admin:staging

  airflow-webserver:
    image: ghcr.io/akdasa-studios/shruti-airflow:staging

  airflow-scheduler:
    image: ghcr.io/akdasa-studios/shruti-airflow:staging

  airflow-worker:
    image: ghcr.io/akdasa-studios/shruti-airflow:staging

  airflow-triggerer:
    image: ghcr.io/akdasa-studios/shruti-airflow:staging

  airflow-init:
    image: ghcr.io/akdasa-studios/shruti-airflow:staging

  couchdb:
    image: ghcr.io/akdasa-studios/shruti-couchdb:staging

  couchdb-init:
    image: ghcr.io/akdasa-studios/shruti-couchdb-init:staging

  gateway:
    image: ghcr.io/akdasa-studios/shruti-gateway:staging
    