"""Clarify worker — a deterministic terminal for a deictic request the server
can't ground because the needed personal context is absent.

Reached from `route_after_router` when the router flagged a deictic pointer at
the user's own listening — «где остановился», «перескажи текущую лекцию»,
«что я слушал на неделе», «что послушать ещё» — but there is NO real anchor to
resolve it against: `current_track_ref` is unset (no lecture open) and/or the
listen-history is empty (`history_summary` is None). Without this the request
fell through to a corpus worker that blind-searches for "the last lecture" and
refuses with a confusing "not found" (#4/#44/#46 family).

Instead we ask ONE short question in the USER's language — generated by the
cheap LLM so every shipped locale is covered, not just a hardcoded pair —
so the next turn is answerable. Terminal → END.
"""

from __future__ import annotations

from langgraph.config import get_stream_writer
from langgraph.runtime import Runtime

from shruti_chat.agent.graph.nodes._worker_common import localized_reply
from shruti_chat.agent.graph.state import ChatState
from shruti_chat.agent.graph.turn_context import TurnContext
from shruti_chat.observability.logging import bind_node_role, get_logger

log = get_logger(__name__)


async def clarify_worker_node(state: ChatState, runtime: Runtime[TurnContext]) -> dict:
    bind_node_role("clarify_worker")
    ctx = runtime.context
    writer = get_stream_writer()
    writer({"type": "status", "data": {"key": "composing_answer"}})

    args = state.get("extracted_args") or {}
    # `current_ref` / `recent_ref` point at a specific lecture; `history_ref`
    # (and the recommend path) are about the listen-log as a whole.
    points_at_lecture = bool(args.get("current_ref") or args.get("recent_ref"))
    if points_at_lecture:
        situation = (
            "The user referred to a specific lecture (their current or last one) "
            "but the app can't see it — nothing is playing and there is no "
            "listening history/sync. Ask them to name the lecture or enable "
            "listening sync so you can continue. No chips."
        )
    else:
        situation = (
            "The user asked about their own listening history / for a "
            "recommendation, but there is no listening history to work from. Ask "
            "them to name a topic, author, or book so you can find lectures. "
            "No chips."
        )
    log.info(
        "clarify_deictic",
        request_id=ctx.request_id,
        kind="which_lecture" if points_at_lecture else "no_history",
        intent=state.get("intent"),
    )
    reply = await localized_reply(ctx, situation)
    if reply.line:
        writer({"type": "delta", "data": {"text": reply.line}})
    return {}
