name: Apps / Mobile

on:
  push:
    branches:
      - main
    paths:
      - "modules/apps/mobile/**"
      - "modules/libs/audioPlayer/**"
      - "scripts/update-envs.py"
      - ".github/workflows/_apps-mobile-build.yml"

concurrency:
  group: mobile-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

env:
  REGISTRY: ghcr.io
  ORGANIZATION: akdasa-studios

jobs:

  # ---------------------------------------------------------------------------- #
  #                               Build Ionc Bundle                              #
  # ---------------------------------------------------------------------------- #

  build-ionic:
    name: 👷‍♂️ Build Ionic App
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release_version.outputs.version }}
      build_number: ${{ steps.release_version.outputs.build_number }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      # ------------------------------- Get Meta Info ------------------------------ #

      - name: Get Version from package.json
        id: release_version
        shell: bash
        run: |
          set -euo pipefail
          version=$(jq -r '.version' modules/apps/mobile/package.json)
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "build_number=$(( GITHUB_RUN_NUMBER + 500 ))" >> "$GITHUB_OUTPUT"

      # -------------------------- Install Dev Environment ------------------------- #

      - name: 🧰 Install Node.js
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: |
            modules/apps/mobile/package-lock.json
            modules/libs/audioPlayer/package-lock.json
    
      # ------------------------------- Configuration ------------------------------ #

      - name: ✏️ Write env.ts
        run: |
          cat << EOF > ./modules/apps/mobile/src/env.ts
          export const ENVIRONMENT = {
            release:             "${{ steps.release_version.outputs.version }}",
            dist:                "${{ steps.release_version.outputs.build_number  }}",
            sentryDsn:           "${{ secrets.SENTRY_DSN }}",
            revenueCatGoogleKey: "${{ secrets.GOOGLE_REVENUE_CAT_KEY }}",
            revenueCatAppleKey:  "${{ secrets.APPLE_REVENUE_CAT_KEY }}",
            amplitudeKey:        "${{ secrets.AMPLITUDE_KEY }}",
            readonlyAuthToken:   "${{ secrets.READONLY_AUTH_TOKEN }}",
            apiUrl:              "${{ vars.API_URL      || 'http://localhost:8101/' }}",
            databaseUrl:         "${{ vars.DATABASE_URL || 'http://localhost:5984/' }}",
            bucketName:          "${{ vars.BUCKET_NAME  || 'shruti-dev' }}",
            iOSClientId:         "${{ vars.OATUH_GOOGLE_IOS_CLIENT_ID }}",
            googleWebClientId:   "${{ vars.OATUH_GOOGLE_WEB_CLIENT_ID }}",
          }
          EOF

      # ----------------------------------- Build ---------------------------------- #

      - name: 👷 Build Audio Player Plugin
        working-directory: modules/libs/audioPlayer
        run: |
          npm ci --no-audit --no-fund --prefer-offline
          npm run build

      - name: 👷 Build Ionic App
        working-directory: modules/apps/mobile
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          BUILD_NUMBER: ${{ steps.release_version.outputs.build_number }}
        run: |
          npm ci --no-audit --no-fund --prefer-offline
          npm run build

      # --------------------------------- Artifacts -------------------------------- #

      - name: ⬇️ Download Database from S3
        working-directory: /tmp
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.BUCKET_REGION_NAME }}
          BUCKET_ENDPOINT_URL: ${{ vars.BUCKET_ENDPOINT_URL }}
          BUCKET_NAME: ${{ vars.BUCKET_NAME }}
        run: |
          set -euo pipefail
          mkdir -p ./databases/

          files=(
            "artifacts/bundled-data/tracks.db"
            "artifacts/bundled-data/tracks.db-mrview-901296fddda39433e93ca2223f2f0cd6"
            "artifacts/bundled-data/tracks.db-mrview-3b9f49811f1b73b6da3d10c5dc9876fb"
            "artifacts/bundled-data/index.db"
            "artifacts/bundled-data/dictionary.db"
          )

          for file in "${files[@]}"; do
            aws --endpoint-url "$BUCKET_ENDPOINT_URL" \
              s3 cp "s3://$BUCKET_NAME/$file" \
              "./databases/$(basename "$file")"
          done
    
      - name: ⬆️ Upload Ionic bundle
        uses: actions/upload-artifact@v4
        with:
          name: apps-mobile-ionic
          path: modules/apps/mobile/dist
          if-no-files-found: error
          retention-days: 5

      - name: ⬆️ Upload Databases bundle
        uses: actions/upload-artifact@v4
        with:
          name: apps-mobile-databases
          path: /tmp/databases
          if-no-files-found: error
          retention-days: 5


  # ---------------------------------------------------------------------------- #
  #                               Build Android App                              #
  # ---------------------------------------------------------------------------- #

  build-android:
    name: 🤖 Build Android App
    runs-on: ubuntu-latest
    needs: [build-ionic]
    defaults:
      run:
        working-directory: modules/apps/mobile

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      # -------------------------- Install Dev Environment ------------------------- #

      - name: 🧰 Install Node.js
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: |
            modules/apps/mobile/package-lock.json
            modules/libs/audioPlayer/package-lock.json

      - name: 📦 Install Node Dependencies
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: 💾 Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 🤖 Install Android SDK
        uses: android-actions/setup-android@v2

      - name: 📝 Accept Android SDK licenses
        shell: bash
        run: yes "" | sdkmanager --licenses || true

      # ------------------------------- Configuration ------------------------------ #

      - name: 📜 Install Android Certificates
        shell: bash
        working-directory: data/keys/apk
        run: echo "${{ secrets.ANDROID_KEYSTORE_FILE }}" | base64 -d > mobile.jks

      - name: ⬇️ Download Ionic bundle
        uses: actions/download-artifact@v4
        with:
          name: apps-mobile-ionic
          path: modules/apps/mobile/dist

      - name: ⬇️ Download Databases bundle
        uses: actions/download-artifact@v4
        with:
          name: apps-mobile-databases
          path: modules/apps/mobile/android/app/src/main/assets/databases

      - name: 🧮 Update Version
        shell: bash
        env:
          VERSION: ${{ needs.build-ionic.outputs.version }}
          BUILD_ID: ${{ needs.build-ionic.outputs.build_number }}
        run: npx trapeze run configuration.yml -y --android

      - name: ⬇️ Sync Capacitor
        run: npx cap sync android

      # ----------------------------------- Build ---------------------------------- #

      - name: 👷 Build Android ABB
        env:
          APPSFLYER_KEY: ${{ secrets.APPSFLYER_KEY }}
        run: |
          npx cap build android \
          --keystorepath ../../../../data/keys/apk/mobile.jks \
          --keystorepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
          --keystorealias ${{ secrets.ANDROID_KEYSTORE_ALIAS }} \
          --keystorealiaspass ${{ secrets.ANDROID_KEYSTORE_ALIAS_PASSWORD }} \
          --androidreleasetype AAB

      # --------------------------------- Artifacts -------------------------------- #
      
      - name: ⬆️ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apps-mobile-android
          path: modules/apps/mobile/android/app/build/outputs/
          if-no-files-found: error
          retention-days: 5
    
  build-ios:
    name: 📱 Build iOS App
    runs-on: macos-15
    needs: [build-ionic]
    defaults:
      run:
        working-directory: modules/apps/mobile

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      # -------------------------- Build Env Dependencies -------------------------- #

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4.0'

      - name: 🧰 Install Node.js
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: |
            modules/apps/mobile/package-lock.json
            modules/libs/audioPlayer/package-lock.json

      - name: 📦 Install Node Dependencies
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: 📦 Install Gem Dependencies
        working-directory: modules/apps/mobile/ios/App
        shell: bash
        run: |
          sudo gem install bundler
          bundle install

      # ----------------------------- App Dependencies ----------------------------- #

      - name: ⬇️ Download Ionic bundle
        uses: actions/download-artifact@v4
        with:
          name: apps-mobile-ionic
          path: modules/apps/mobile/dist

      - name: ⬇️ Download Databases bundle
        uses: actions/download-artifact@v4
        with:
          name: apps-mobile-databases
          path: modules/apps/mobile/ios/App/App/databases

      - name: ⬇️ Sync Capacitor
        run: npx cap sync ios

      - name: 📜 Install iOS Certificates
        shell: bash
        working-directory: modules/apps/mobile/ios/App/fastlane
        run: |
          echo ${{ secrets.APPLE_CERTIFICATES }} | base64 -d > output.zip && unzip output.zip

      # --------------------------------- Build App -------------------------------- #

      - name: 👷 Build iOS App
        working-directory: modules/apps/mobile/ios/App
        env:
          VERSION: ${{ needs.build-ionic.outputs.version }}
          BUILD_NUMBER: ${{ needs.build-ionic.outputs.build_number }}
          BETA_FEEDBACK_EMAIL: ${{ secrets.BETA_FEEDBACK_EMAIL }}
          BETA_CONTACT_FIRST_NAME: ${{ secrets.BETA_CONTACT_FIRST_NAME }}
          BETA_CONTACT_LAST_NAME: ${{ secrets.BETA_CONTACT_LAST_NAME }}
          BETA_CONTACT_PHONE_NUMBER: ${{ secrets.BETA_CONTACT_PHONE_NUMBER }}
          APPLE_STORE_TEAM_ID: ${{ secrets.APPLE_STORE_TEAM_ID }}
          APPLE_STORE_CONNECT_API_KEY: ${{ secrets.APPLE_STORE_CONNECT_API_KEY }}
          APPLE_STORE_CONNECT_API_KEY_ID: ${{ secrets.APPLE_STORE_CONNECT_API_KEY_ID }}
          APPLE_STORE_CONNECT_API_KEY_ISSUER: ${{ secrets.APPLE_STORE_CONNECT_API_KEY_ISSUER }}
          BUCKET_NAME: ${{ vars.BUCKET_NAME }}
          BUCKET_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY_ID }}
          BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}
          BUCKET_ENDPOINT_URL: ${{ vars.BUCKET_ENDPOINT_URL }}
          BUCKET_REGION_NAME: ${{ vars.BUCKET_REGION_NAME }}
        run: |
          bundle exec fastlane staging

        
      # --------------------------------- Artifacts -------------------------------- #

      - name: ⬆️ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apps-mobile-ios
          path: modules/apps/mobile/ios/App/App.ipa
          if-no-files-found: error
          retention-days: 5
