name: Services / CouchDB / Init

on:
  push:
    paths:
      - "modules/services/couchdb/init/**"
      - ".github/workflows/services-couchdb-init.yml"
  
env:
  REGISTRY: ghcr.io
  ORGANIZATION: jiva-studio

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Build CouchDB Init
        uses: ./.github/actions/build-container
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: modules/services/couchdb/init/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/shruti-couchdb-init:latest
      
      - name: ⬆️ Push Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/shruti-couchdb-init:latest
