name: Services / Gateway

on:
  push:
    paths:
      - "modules/services/gateway/**"
      - ".github/workflows/services-gateway.yml"
  
env:
  REGISTRY: ghcr.io
  ORGANIZATION: akdasa-studios

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: 👷‍♂️ Build Container
        uses: ./.github/actions/build-container
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: modules/services/gateway/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/shruti-gateway:latest
      
      - name: ⬆️ Push Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/shruti-gateway:latest
