"""POST /title — generate a compact chat session title in the background.

The mobile app falls back to `deriveTitle(firstUserMessage)` while a
session is fresh; this endpoint replaces that with a 3-5 word title
generated by a cheap LLM (gemini-flash) once an assistant reply exists.
Called fire-and-forget after the first chat round-trip.
"""

from __future__ import annotations

from typing import Literal

from fastapi import APIRouter, Depends, Header, HTTPException, Request
from pydantic import BaseModel, Field

from shruti_chat.agent import llm
from shruti_chat.api._auth import get_current_user
from shruti_chat.application.cache_helpers import TTL_30D, cached_str
from shruti_chat.composition import AppDeps, get_deps
from shruti_chat.config import get_settings
from shruti_chat.infra.auth.jwt_verifier import VerifiedUser
from shruti_chat.observability.logging import get_logger

log = get_logger(__name__)

router = APIRouter()


class TitleMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str


class TitleRequest(BaseModel):
    messages: list[TitleMessage] = Field(min_length=1, max_length=8)
    lang: Literal["ru", "en"] = "ru"


class TitleResponse(BaseModel):
    # Nullable on purpose — `/title` is called fire-and-forget by the
    # mobile client. An LLM failure is not an error from the client's
    # POV: it falls back to the truncated-first-message title and
    # schedules a foreground retry. Returning 200 with null is more
    # honest than 502, and avoids the toast-on-startup that 5xx would
    # trigger through the generic error path.
    title: str | None = None


_SYSTEM = {
    "ru": (
        "Сформулируй заголовок чата на основе ВОПРОСА ПОЛЬЗОВАТЕЛЯ "
        "(строки начинаются с 'USER:'). Ответ ассистента (ASSISTANT:) — "
        "только контекст для уточнения темы, его суммировать НЕ нужно.\n\n"
        "Требования:\n"
        "- 3-5 слов, регистр предложения\n"
        "- без кавычек, эмодзи, точки/!/? в конце\n"
        "- без слов 'лекция', 'Прабхупада', 'запрос', 'поиск' "
        "(это и так чат о лекциях)\n"
        "- нейтрально, без кликбейта\n"
        "- если в переписке нет содержательной темы (приветствие, "
        "тест, односложное сообщение) — верни ровно: Новый чат\n\n"
        "Ответ — ТОЛЬКО заголовок, без пояснений."
    ),
    "en": (
        "Generate a chat title based on the USER's QUESTION (lines "
        "starting with 'USER:'). The assistant reply (ASSISTANT:) is "
        "context only — do NOT summarise it.\n\n"
        "Requirements:\n"
        "- 3-5 words, sentence case\n"
        "- no quotes, no emoji, no trailing period / ! / ?\n"
        "- avoid the words 'lecture', 'Prabhupada', 'about', 'search' "
        "(it's already a chat about lectures)\n"
        "- neutral, no clickbait\n"
        "- if the conversation has no substantive topic (greeting, test, "
        "one-word message), return exactly: New chat\n\n"
        "Reply with the title ONLY."
    ),
}


def _fallback_title(lang: str) -> str:
    return "New chat" if lang == "en" else "Новый чат"


def _check_app_token(token: str | None) -> None:
    expected = get_settings().app_shared_token
    if not token or token != expected:
        raise HTTPException(status_code=401, detail="invalid app token")


def _clean(raw: str) -> str:
    """Strip quotes, trailing punctuation, control whitespace."""
    s = raw.strip()
    # Some models still wrap in quotes despite the prompt.
    for q in ("\"", "«", "»", "“", "”", "'", "`"):
        if s.startswith(q): s = s[len(q):]
        if s.endswith(q):   s = s[: -len(q)]
    s = s.strip().rstrip(".,;:!?")
    return s[:80]


@router.post("/title", response_model=TitleResponse)
async def title(
    request: Request,
    body: TitleRequest,
    x_app_token: str | None = Header(default=None),
    idempotency_key: str | None = Header(default=None),
    user: VerifiedUser = Depends(get_current_user),
    deps: AppDeps = Depends(get_deps),
) -> TitleResponse:
    _check_app_token(x_app_token)
    settings = get_settings()
    if idempotency_key:
        log.info("title_request", user_id=user.id, idempotency_key=idempotency_key)

    # Separate quota bucket from /chat so heavy title traffic from a flaky
    # client retrying many fresh sessions can't drain the main chat quota.
    ip = request.client.host if request.client else "unknown"
    rl = await deps.rate_limiter.check_and_increment(
        user.id, user.anonymous, ip, scope="title",
    )
    if not rl.allowed:
        raise HTTPException(
            status_code=429,
            detail={
                "code": rl.code,
                "limit": rl.limit,
                "current": rl.current,
                "key_type": rl.key_type,
                "scope": "title",
            },
            headers={"Retry-After": str(rl.retry_after or 60)},
        )

    convo = "\n\n".join(
        f"{m.role.upper()}: {m.content.strip()}"
        for m in body.messages
        if m.content.strip()
    )
    sys_msg = _SYSTEM.get(body.lang, _SYSTEM["en"])

    async def _call_llm() -> str:
        try:
            resp = await llm.acompletion(
                model=settings.llm_outline,  # gemini-2.0-flash — cheap and fast
                messages=[
                    {"role": "system", "content": sys_msg},
                    {"role": "user", "content": convo},
                ],
                # 0.1 — titles want determinism, not creativity. 3-5 words
                # have no useful variance.
                temperature=0.1,
                # ~24 tokens covers 5 RU/EN words with comfortable headroom;
                # any LLM that runs longer is hallucinating decoration.
                max_tokens=24,
            )
            return resp.choices[0].message.content or ""
        except Exception as exc:
            log.warning("title_llm_failed", error=str(exc))
            return ""

    if deps.kv_cache is not None:
        raw = await cached_str(
            deps.kv_cache,
            ns="title",
            key_parts={
                "convo": convo,
                "lang": body.lang,
                "model": settings.llm_outline,
            },
            ttl_s=TTL_30D,
            factory=_call_llm,
        )
    else:
        raw = await _call_llm()

    cleaned = _clean(raw)
    if not cleaned:
        log.warning("title_llm_empty")
        return TitleResponse(title=None)
    return TitleResponse(title=cleaned)
