"""POST /title — generate a compact chat session title in the background.

The mobile app falls back to `deriveTitle(firstUserMessage)` while a
session is fresh; this endpoint replaces that with a 3-5 word title
generated by a cheap LLM (gemini-flash) once an assistant reply exists.
Called fire-and-forget after the first chat round-trip.
"""

from __future__ import annotations

from typing import Literal

from fastapi import APIRouter, Header, HTTPException, Request
from pydantic import BaseModel, Field

from shruti_chat.agent import llm
from shruti_chat.config import get_settings
from shruti_chat.observability.logging import get_logger
from shruti_chat.ratelimit import check_and_increment

log = get_logger(__name__)

router = APIRouter()


class TitleMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str


class TitleRequest(BaseModel):
    messages: list[TitleMessage] = Field(min_length=1, max_length=8)
    lang: Literal["ru", "en"] = "ru"


class TitleResponse(BaseModel):
    title: str


_SYSTEM = {
    "ru": (
        "Ты задаёшь короткий заголовок для чата (3-5 слов, без кавычек, "
        "без точки в конце, регистр предложения). Дай суть запроса "
        "пользователя, без воды. Ответь ТОЛЬКО заголовком — без объяснений."
    ),
    "en": (
        "Generate a short chat title (3-5 words, no quotes, no trailing "
        "period, sentence case). Capture the gist of the user's request. "
        "Reply with the title ONLY."
    ),
}


def _check_app_token(token: str | None) -> None:
    expected = get_settings().app_shared_token
    if not token or token != expected:
        raise HTTPException(status_code=401, detail="invalid app token")


def _check_device_id(device_id: str | None) -> str:
    if not device_id:
        raise HTTPException(status_code=400, detail="missing X-Device-Id header")
    return device_id


def _clean(raw: str) -> str:
    """Strip quotes, trailing punctuation, control whitespace."""
    s = raw.strip()
    # Some models still wrap in quotes despite the prompt.
    for q in ("\"", "«", "»", "“", "”", "'", "`"):
        if s.startswith(q): s = s[len(q):]
        if s.endswith(q):   s = s[: -len(q)]
    s = s.strip().rstrip(".,;:!?")
    return s[:80]


@router.post("/title", response_model=TitleResponse)
async def title(
    request: Request,
    body: TitleRequest,
    x_app_token: str | None = Header(default=None),
    x_device_id: str | None = Header(default=None),
) -> TitleResponse:
    _check_app_token(x_app_token)
    device_id = _check_device_id(x_device_id)
    settings = get_settings()

    # Separate quota bucket from /chat so heavy title traffic from a flaky
    # client retrying many fresh sessions can't drain the main chat quota,
    # and a leaked app_shared_token (it ships in every APK) can't be used
    # to bill unlimited /title calls.
    ip = request.client.host if request.client else "unknown"
    rl = await check_and_increment(device_id, ip, scope="title")
    if not rl.allowed:
        raise HTTPException(
            status_code=429,
            detail={
                "code": rl.code,
                "limit": rl.limit,
                "current": rl.current,
                "key_type": rl.key_type,
                "scope": "title",
            },
            headers={"Retry-After": str(rl.retry_after or 60)},
        )

    convo = "\n\n".join(
        f"{m.role.upper()}: {m.content.strip()}"
        for m in body.messages
        if m.content.strip()
    )
    sys_msg = _SYSTEM.get(body.lang, _SYSTEM["en"])

    try:
        resp = await llm.acompletion(
            model=settings.llm_outline,  # gemini-2.0-flash — cheap and fast
            messages=[
                {"role": "system", "content": sys_msg},
                {"role": "user", "content": convo},
            ],
            temperature=0.3,
            max_tokens=40,
        )
        raw = resp.choices[0].message.content or ""
    except Exception as exc:
        log.warning("title_llm_failed", error=str(exc))
        raise HTTPException(status_code=502, detail="title generation failed")

    cleaned = _clean(raw)
    if not cleaned:
        raise HTTPException(status_code=502, detail="empty title")
    return TitleResponse(title=cleaned)
